controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    # Frame IDs
    odom_frame_id: odom
    base_frame_id: base_link

    # Wheel configuration
    left_wheel_names: ['body_to_left_back_wheel', 'body_to_left_front_wheel']
    right_wheel_names: ['body_to_right_back_wheel', 'body_to_right_front_wheel']
    wheel_separation: 1.1
    wheel_radius: 0.2

    # Enable odometry TF publishing
    enable_odom_tf: true
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    use_stamped_vel: false
    open_loop: false